/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package template

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun `test runs`() {
        assertEquals(1, 1)
    }
}
